#INITIAL SETTINGS
data_source: 
  directory: ../Dataset/
  filename: winequality-red.csv
  column_names: ['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality']
  drop_columns:
  target_name: quality
  test_size: 0.2
  random_state: 1000


#Logistic Regression
model_1: 
  class_weight: balanced
  estimator : logreg
  scoring: recall
  cv: 10
  verbose: 3
  n_jobs: -1
  solver: ['liblinear']
  model_directory: ../Model/
  model_name: logreg_model.pkl

  #Random Forest
model_2: 
  n_estimator: 100
  estimator: 
  scoring: recall
  cv: 10
  verbose: 3
  n_jobs: -1
  model_directory: ../Model/
  model_name: rf_model.pkl

  #Decision Tree
model_3:
  estimator:
  scoring: recall
  cv: 10
  verbose: 3
  n_jobs: -1
  model_directory: ../Model/
  model_name: dt_model.pkl.pkl