name: Python application

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        env:
          PATH_FILE: winepredict
          API_SERVICE_IMAGE: winepredict-api
          STREAMLIT_SERVICE_IMAGE: winepredict-streamlit
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "mkdir -p temp"
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "git clone https://github.com/ariprachmaan/winepredict.git temp"
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "rsync -a temp/ $PATH_FILE"
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "rm -rf temp/"
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd $PATH_FILE && docker-compose down"
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd $PATH_FILE && docker-compose build"
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd $PATH_FILE && docker-compose up -d"
